### PR TITLE
Packet Diagram Implementations 

### PR DESCRIPTION
**Pull request by sthagen**
# Changes:

- [x] added developer documentation to help the other editors get started and to describe the envisioned workflow
- [x] added rasterized diagrams derived from the four available package diagrams
- [x] added sources for the diagrams of the first eleven packets as per specification draft
- [x] added SVG renditions of all package diagrams available as [`bytefield-svg`](https://github.com/Deep-Symmetry/bytefield-svg) sources yet
- [x] copied the style of bit position background, labeling of columns and rows, as well as background for optional package names and optional package contents
- [x] experimental replacement of the term `OPTIONAL` with `?` for some fields
- [x] proposed a better way to describe optional fields that are followed by required fields and mess with the offsets of these subsequent fields
- [x] proposed a better way for trailing multi-byte payload parts of different sizes (split diagrams into diagrams per variant for clarity) 
- [x] proposed a slightly more focused design of the row and column headers to best highlight the package structure instead of adding repeated labels to the "margin cells"
- [x] small textual fix (`GwAddress` &rightarrow; `GwAdd`) to align surrounding prose with diagram terms
- [x] the width of the fields is now consistent and not skewed as in the draft as of June 2024 when there are multi-bit fields mixed with single bit fields

## Packets implemented (All plus proposed):

- [x] 3.1.1 `ADVERTISE`
- [x] 3.1.2 `SEARCHGW`
- [x] 3.1.3 `GWINFO`
- [x] 3.1.4 `CONNECT`
- [x] 3.1.5 `CONNACK`
- [x] 3.1.6 `AUTH`
- [x] 3.1.7 `REGISTER`
- [x] 3.1.8 `REGACK`
- [x] 3.1.9 n/a (intro of the subsequent publish variants)
- [x] 3.1.10 `PUBWOS`
- [x] 3.1.11 `PUBLISH-QoS-0`
- [x] 3.1.12 `PUBLISH-QoS-1-AND-2`
- [x] 3.1.13 `PUBACK`
- [x] 3.1.14 `PUBREC` (QoS 2 delivery part 1)
- [x] 3.1.15 `PUBREL` (QoS 2 delivery part 2)
- [x] 3.1.16 `PUBCOMP` (QoS 2 delivery part 3)
- [x] 3.1.17.a `SUBSCRIBE` (Variant with Topic Data in Payload)
- [x] 3.1.17.b `SUBSCRIBE` (Variant with Topic Filter in Payload)
- [x] 3.1.18 `SUBACK`
- [x] 3.1.19.a `UNSUBSCRIBE` (Variant with Topic Data in Payload)
- [x] 3.1.19.b `UNSUBSCRIBE` (Variant with Topic Filter in Payload)
- [x] 3.1.20 `UNSUBACK`
- [x] 3.1.21 `PINGREQ`
- [X] 3.1.22 `PINGRESP`
- [X] 3.1.23 `DISCONNECT`
- [x] 3.1.24 `WAKEUP`
- [x] 3.1.25 Forwarder Encapsulation
- [x] 3.1.26 Protection Encapsulation

Signed-off-by: Stefan Hagen <stefan@hagen.link>

### CODE REVIEW

**Comment by simon622** [comment]
Happy to approve, but I don't have reviewer rights

**Review by lenzarda — CHANGES_REQUESTED** [review]
Great job!
I would recommend to replace "?" with "opt" or "optional".
In case of multiple optional fields like the CONNACK packet I would recommend to use a parametric approach like 10=X, 10+5=Y and replace 11 with X+Y or, in alternative, follow the same approach used for DISCONNECT (with parametric values defined in each field). Also because in CONNACK the length of the "Auth Data" field is determined by the previous two.
In CONNACK and in CONNECT the "Auth Data" field should be represented as draw-gap as it is over multiple bytes.
In CONNECT the "Will Payload" field should be represented as draw-gap as it is over multiple bytes.
In the Protection Encapsulation Packet we should use "Protected MQTT-SN Packet" and not "MQTT SN Packet" as the packet may be encrypted.

**Comment by sthagen** [comment]
implementation status of feedback:

- [x] replace "?" with "opt" or "optional".
- [x] In the Protection Encapsulation Packet "Protected MQTT-SN Packet" &leftarrow; "MQTT SN Packet" as the packet may be encrypted.
- [ ] In case of multiple optional fields like the CONNACK packet I would recommend to use a parametric approach like 10=X, 10+5=Y and replace 11 with X+Y or, in alternative, follow the same approach used for DISCONNECT (with parametric values defined in each field). Also because in CONNACK the length of the "Auth Data" field is determined by the previous two.
- [ ] In CONNACK and in CONNECT the "Auth Data" field should be represented as draw-gap as it is over multiple bytes.
- [ ] In CONNECT the "Will Payload" field should be represented as draw-gap as it is over multiple bytes.
- [ ] Decision on placement of the `[OPT]` indicator as roman or cursive font?

**Comment by sthagen** [comment]
I think I applied the review feedback ten days ago and will go ahead and merge.
This way I can use the diagrams in the markdown format of the editor document.

Any additional changes we can easily apply during the normal editorial cycles.

**Comment by lenzarda** [comment]
@sthagen I agree with the font used for [OPT]
As the content has been already merged into the draft document. I will add my comments directly over there

**Comment by sthagen** [comment]
@lenzarda thanks. I will create a little additional PR to add diagrams for the special packet parts in the section before the control packets.

**Pull request merged**
